version: "3.8"

services:
  mongo_db:
    image: mongo
    container_name: tp1_fernandez_marchetti_db
    volumes:
      - mongo_db_data:/data/db
    ports:
      - "27017:27017"

  backend:
    build: ./tp1_fernandez_marchetti_backend
    image: backend
    ports:
      - "3000:3000"
    env_file:
      - ./tp1_fernandez_marchetti_backend/.env
    depends_on:
      - mongo_db

  frontend:
    build: ./tp1_fernandez_marchetti_frontend
    image: frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  mongo_db_data:
